### ISSUE TITLE
✨ Provide an option to specify the supported QIR profile

### ISSUE THREAD

**Issue by burgholzer** [Munich-Quantum-Software-Stack/QDMI#115]
Right now, there is no way for a device to specify which QIR profile it supports.
It should be easy enough to add this as another device property that has a string value.
As far as I am aware, the only possible values for that string at the moment would be `"base_profile"` and `"adaptive_profile"`.

This is slightly in contrast to how we handle the support for OpenQASM where we offer separate enum values for OpenQASM 2 and OpenQASM 3 support.
However, I do think this makes sense since OpenQASM 3 isn't really a superset of OpenQASM 2 in the way that the adaptive QIR profile is a superset of the base profile.

**Comment by ystade** [comment]
If I understand that correctly, you would add this functionality so that it can be queried via `qdmi_query_device_property`. That is another difference to how the compatibility with OpenQASM2 or 3 is dealt with.

The answer is probably no but would it be enough that the device receives the QIR input and decides whether it can handle it or not based on the concrete input? One argument in favour of that is that those profiles can become quite specific and hard to standardise the capabilities of the device with respect to the supported profile.

Besides, I am a bit unsure how future-proof a string valued capability is. If we want to standardize that at some point with properly defined ENUM values, that might become hard.

**Comment by burgholzer** [comment]
> If I understand that correctly, you would add this functionality so that it can be queried via `qdmi_query_device_property`. That is another difference to how the compatibility with OpenQASM2 or 3 is dealt with.

Yes. That is how I would have implemented that.

> The answer is probably no but would it be enough that the device receives the QIR input and decides whether it can handle it or not based on the concrete input? One argument in favour of that is that those profiles can become quite specific and hard to standardise the capabilities of the device with respect to the supported profile.

Hm. It would keep things simple, but I believe from the perspective of the software stack, there probably needs to be a way to filter devices that support a certain format. 
Maybe that's a hypothetical scenario though.

> Besides, I am a bit unsure how future-proof a string valued capability is. If we want to standardize that at some point with properly defined ENUM values, that might become hard.

It's probably not really future-proof at all. I totally agree with you.
I think one of the bigger problems is that, right now, there are so many different levels of support for QIR (and, in fact, OpenQASM 3 as well), but none of these are standardized so that we could be exposing them as an identifier.

What we could do short-term:
The `QDMI_control_create_job` semantics already describe that the function indicates whether a format is (not) supported. We could slightly adjust the semantics so that it is ok to call this function with a `NULL` program and `NULL` job handle to just check for the support without allocating/parsing anything. (This should be implemented in the example devices and tested)
In addition, we could split the current `QIR` enum value into separate `QIRBASE` and `QIRADAPTIVE` values to allow distinguishing between them.

**Comment by ystade** [comment]
I share your concerns and support both proposals in the last paragraph. 👍

**Comment by echavarria-mqv** [comment]
I agree with @burgholzer:

> > The answer is probably no but would it be enough that the device receives the QIR input and decides whether it can handle it or not based on the concrete input? One argument in favour of that is that those profiles can become quite specific and hard to standardise the capabilities of the device with respect to the supported profile.
> 
> Hm. It would keep things simple, but I believe from the perspective of the software stack, there probably needs to be a way to filter devices that support a certain format.
> Maybe that's a hypothetical scenario though.

I believe a compiler should leverage this information during compilation to 1) maximize the offloading of jobs that fully align with the target backend's capabilities while 2) minimizing the likelihood of job cancellations.
