### ISSUE TITLE
Type of coupling map

### ISSUE THREAD

**Issue by denialhaag** [Munich-Quantum-Software-Stack/QDMI#119]
If I'm not mistaken, the [type of the coupling map of the example device](https://github.com/Munich-Quantum-Software-Stack/QDMI/blob/develop/examples/device/cxx/device.cpp#L145) does not comply with the [type specified in enums.h](https://github.com/Munich-Quantum-Software-Stack/QDMI/blob/develop/include/qdmi/common/enums.h#L45). We are currently working on implementing the query interface and were wondering whether the coupling map should be a list of `int`s or a list of `QDMI_Device_Site`s.

**Comment by ystade** [comment]
Thanks, @denialhaag, for discovering that bug. It was a bug in the documentation, and it is supposed to be a list of `QDMI_Sites` as the implementation of the examples showcases. We fixed the inconsistency in the documentation in #120.
