### ISSUE TITLE
Levels of calibration

### ISSUE THREAD

**Issue by echavarria-lrz** [Munich-Quantum-Software-Stack/QDMI#14]
https://github.com/Munich-Quantum-Software-Stack/QDMI/blob/4d4d0dc7c8331f0b2dc43119f2da0a53d2a5c203/src/qdmi_stubs.c#L182

Some devices, like planqc's, support levels of calibration. We should include this as an argument to `QDMI_device_quality_calibrate`

**Comment by burgholzer** [comment]
Closing this for now. 
Once we are ready to do so: let's create a corresponding _discussion_ on the calibration interface and, afterwards, implement the respective solution.
