### ISSUE TITLE
Link to our own license, not LLVM's

### ISSUE THREAD

**Issue by echavarria-mqv** [Munich-Quantum-Software-Stack/QDMI#94]
https://github.com/Munich-Quantum-Software-Stack/QDMI/blob/d30ebfa0e045de028df064bb1ed377bb8c9bdb19/include/qdmi/client.h#L3

Do we need to link to [LLVM's license](https://llvm.org/LICENSE.txt)?

Shouldn't we link to our [own license](https://github.com/Munich-Quantum-Software-Stack/QDMI/blob/develop/LICENSE) (which happens to be Apache 2.0 with LLVM exceptions) or [Apache's template](https://www.apache.org/licenses/LICENSE-2.0)?

**Comment by burgholzer** [comment]
Linking to our own license makes sense here 👍🏼 can be combined with a fix for #95
