### ISSUE TITLE
QDMI info in license

### ISSUE THREAD

**Issue by echavarria-mqv** [Munich-Quantum-Software-Stack/QDMI#95]
https://github.com/Munich-Quantum-Software-Stack/QDMI/blob/d30ebfa0e045de028df064bb1ed377bb8c9bdb19/LICENSE#L189

Don't we need to update this?

**Comment by burgholzer** [comment]
Yes, we probably should. Although the original LLVM license also leaves this blank.
Should we just use "The QMDI contributors" with a link to https://github.com/Munich-Quantum-Software-Stack/QDMI/graphs/contributors?
Can someone quickly scout best-practices on GitHub for that?
I'd like to avoid listing explicit names as this information gets out of date so quickly.

**Comment by ystade** [comment]
This exact line is *not* supposed to be replaced. Instead, the entire boilerplate is meant to be copied to source files while substituting the placeholders. 

See #97.
