### ISSUE TITLE
User management and access control using sessions

### ISSUE THREAD

**Issue by mnfarooqi** [Munich-Quantum-Software-Stack/QDMI#96]
@burgholzer @echavarria-lrz  

`QDMI_session_alloc` is the first function called by a client. However, the function signature doesn't contain anything to pass information about the user/client that is needed for user management and access control when a session is allocated/created. 

Is there any other way for a driver to get this information?

Suggested solution:
The `QDMI_session_alloc` signature can be modified to add a QInfo object as input, which the user can use to pass the required information.

**Comment by burgholzer** [comment]
I can confirm that this is not currently possible and will probably require certain additions and/or modifications to the driver's session interface.
If possible, I'd like to avoid the QInfo dependency as we have now designed the interface in a way where QInfo is not needed anywhere else so far.
However, I believe something very similar to the way how job parameters are handled at the moment could also work here.
We'll follow up on that in a bit.

**Comment by ystade** [comment]
I can only agree with what @burgholzer said. So far, it is not possible, but in future versions, this ability must definitely be added to the interface.
@mnfarooqi, may I ask which information exactly would need to be passed from the client to the session? Is it just a token, is it more, or does it change depending on the situation?

**Comment by mnfarooqi** [comment]
It doesn't have to be a `QInfo` object, just something that can be used to pass the information. Depending on the driver implementation, it can be anything that identifies a user or client's access privileges, e.g. a token or a userid. An opaque type for user?

I was wondering how to implement `user management and access control` in the current version, as there is nothing in the example implementation, although it is mentioned in the documentation. If there is no provision for this, would an explicit statement that `user management and access control` is not yet possible be more appropriate?

**Comment by ystade** [comment]
I like the idea of an opaque type for a user.

That is a good point, that we should state that more explicitly in the documentation.

**Comment by burgholzer** [comment]
> I like the idea of an opaque type for a user.

I think I also like that idea.
That type would be defined by the driver.
And the session allocation function would take a User as a parameter.
Just begs the questions:
- how one creates a user (probably related to authentication)
- how different drivers can expose different kinds of users (and probably functions that clients can use for authentication, etc.)
- ... probably more

**Comment by mnfarooqi** [comment]
The purpose here is to pass some kind of access control information to the session to help it set the permissions (no-access/read-only/read-write) on the devices when a client creates a session. 
The responsibility for user creation and authentication can be assumed by the driver developers (e.g. hosting sites) using their existing mechanisms.

**Comment by burgholzer** [comment]
> The purpose here is to pass some kind of access control information to the session to help it set the permissions (no-access/read-only/read-write) on the devices when a client creates a session. 
> 
> The responsibility for user creation and authentication can be assumed by the driver developers (e.g. hosting sites) using their existing mechanisms.

In that case, it might be enough to mirror what we do for job parameters at the moment. A job is created, then parameters can be set, then it is submitted,
Similarly, a session can be allocated, then parameters could be set on the session, and finally, the driver can use that information when issuing the available devices to the client.

**Comment by mnfarooqi** [comment]
Yes, we can do that to keep the interface consistent.

I'll put together a pull request.

**Comment by burgholzer** [comment]
> Yes, we can do that to keep the interface consistent.
> 
> I'll put together a pull request.

Thanks! Much appreciated 🙏🏼
